# Generated by Django 4.2.2 on 2023-09-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalStore', '0006_auto_20190403_1046'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table='medicalstore_medicine',
        ),
    ]
