# Generated by Django 4.2.2 on 2023-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='AppointmentTimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
