# Generated by Django 4.2.2 on 2023-09-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0002_alter_appointment_appointmenttimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='AppointmentTimeStamp',
            field=models.DateTimeField(auto_now_add=True, db_column='appointmenttimestamp'),
        ),
    ]
