# Generated by Django 4.2.2 on 2023-07-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0025_appointment_appointmenttimestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='MornAftNight',
            field=models.CharField(default=101, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='NoOfDays',
            field=models.CharField(default=5, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='beforeafter',
            field=models.CharField(default='after', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(default='paracetamol', max_length=200),
            preserve_default=False,
        ),
    ]
