# Generated by Django 4.2.2 on 2023-07-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0026_prescription_mornaftnight_prescription_noofdays_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicineName', models.CharField(max_length=200)),
                ('beforeAfter', models.CharField(max_length=200)),
                ('Morning', models.CharField(max_length=200)),
                ('Afternoon', models.CharField(max_length=200)),
                ('Night', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='MornAftNight',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='beforeafter',
        ),
    ]
