# Generated by Django 4.2.2 on 2023-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0027_medicine_remove_prescription_mornaftnight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ManyToManyField(to='HealthCentre.medicine'),
        ),
    ]
